### DISCUSSION TITLE
Not able to see sensor in Energy dashboard

### DISCUSSION THREAD

**Discussion by rik246810** [skelgaard/homeassistant-apsystems#9] [General]
Hello,
I'm not able to see the `sensor.apsystems energy day `in the energy dashboard. How can I fix this?

**Comment by synack666** [comment]
Hi, you have to set device_class and state_class in customize.yaml

```
sensor.apsystems_energy_day:
  device_class: energy
  state_class: total_increasing
```

**Comment by Machiel92** [comment]
That did the trick!
Cool cool!

Now i'm going to look if it's possible to inport the total generated power into home assistant.

**Comment by sjakief** [comment]
Hi,
I can see the sensors ( 5 sensors, 1 date sensor,2 kwh and 2 kw sensors from developer menu, and the values are being filled
![afbeelding](https://user-images.githubusercontent.com/12416263/158465628-f1951a29-e66a-4223-95df-9b7b17de600a.png)

In my separate config file I put this: 
`sensor.apsystems_energy_day:
  device_class: energy
  state_class: total_increasing

sensor.apsystems_energy_latest:
  device_class: energy

sensor.apsystems_energy_total:
  device_class: energy

sensor.apsystems_power_max_day:
  device_class: energy

sensor.apsystems_power_latest:
  device_class: energy`

I can still see nothing to add in my energy dashboard.
can someone explain what I am doing wrong?

**Comment by maprolim** [comment]
Another way is to create a Template Sensor that use the original sensor as reference:

To do that, put this lines in the configuration.yaml

```
template:
  - sensor:
      - name: "Energy APS Day MOD"
        unit_of_measurement: 'kWh'
        state: >
          {{ (states("sensor.apsystems_energy_day") | float) | round(2) }}       
        device_class: energy
        state_class: total_increasing
        attributes:         
          last_reset: '1970-01-01T00:00:00+00:00'
```
